# from pydantic_settings import BaseSettings


# class BattleConfigs(BaseSettings):
#     team: ...
#     select: ...
#     battle_result: ...
#     status_bar: ...
#     replay: ...
#     water: ...
#     fire: ...
#     earth: ...
#     common: ...
#     heal: ...
